# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 15:57
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=15, verbose_name='标题')),
                ('category', models.CharField(max_length=8, verbose_name='分类')),
                ('hint_count', models.IntegerField(default=0, verbose_name='点击数')),
                ('background_img', models.ImageField(blank=True, upload_to='images/bg_img/')),
                ('abstract', models.TextField(blank=True, verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
